### ISSUE TITLE
Should the `port` field in server part need to be `required`?

### ISSUE THREAD

**Issue by xilin** [stephenwzl/enginx#1]
It seems the `port` field can be optional.

**Comment by stephenwzl** [comment]
Thanks for following this project.
sure, `port` field should be optional.

To implement this feature, you need to change the syntax in the `Lexer`. (see in https://github.com/stephenwzl/enginx/blob/master/Lexer/enginx.y#L43)
Then change function `enginx_create_server` to make `port` optional at runtime.

I have stopped developing new features for this project, but it is still used by some App with millions of users, so don't worry about its stability.

**Comment by xilin** [comment]
Got it, thanks.
